#!/bin/bash
# ME_CAM COMPLETE FIX - ALL COMMANDS IN ONE PLACE
# Copy & paste each section into your Pi terminal

echo "═══════════════════════════════════════════════════════════════"
echo "   ME_CAM COMPLETE FIX - COPY/PASTE COMMANDS"
echo "   For Raspberry Pi - January 13, 2026"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ═══════════════════════════════════════════════════════════════
# QUICK START (RUN THIS FIRST - 2 MINUTES)
# ═══════════════════════════════════════════════════════════════

echo "🚀 QUICK START (Copy entire block and paste):"
echo ""
echo "------- COPY FROM HERE -------"
cat << 'EOF'
ssh pi@raspberrypi.local
cd ~/ME_CAM-DEV
git pull origin main
sudo apt install -y python3-picamera2
mkdir -p ~/ME_CAM-DEV/recordings
chmod 755 ~/ME_CAM-DEV/recordings
sudo systemctl restart mecamera
sleep 5
echo "✅ Deployed! Now:"
echo "1. Open: http://raspberrypi.local:8080"
echo "2. Click: ⚙️ Configure"
echo "3. Scroll to: ⚡ Performance Settings (GREEN)"
echo "4. Check: ✓ Use Fast Streaming"
echo "5. Set FPS: 15"
echo "6. Save Settings"
EOF
echo "------- END COPY -------"
echo ""
echo ""

# ═══════════════════════════════════════════════════════════════
# DETAILED COMMANDS (If you want to understand each step)
# ═══════════════════════════════════════════════════════════════

echo "═══════════════════════════════════════════════════════════════"
echo "📍 STEP 1: SSH TO YOUR PI"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "ssh pi@raspberrypi.local"
echo ""
echo "----> You should see: pi@raspberrypi:~ $"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📥 STEP 2: UPDATE CODE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "cd ~/ME_CAM-DEV"
echo "git pull origin main"
echo ""
echo "----> You should see: 'Already up to date' or some files updated"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📦 STEP 3: INSTALL FAST STREAMING LIBRARY"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "sudo apt update"
echo "sudo apt install -y python3-picamera2"
echo ""
echo "# Verify it worked:"
echo "python3 -c \"from picamera2 import Picamera2; print('✅ Success!')\""
echo ""
echo "----> Should show: ✅ Success!"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📁 STEP 4: CREATE RECORDINGS DIRECTORY"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "mkdir -p ~/ME_CAM-DEV/recordings"
echo "chmod 755 ~/ME_CAM-DEV/recordings"
echo "ls -la ~/ME_CAM-DEV/ | grep recordings"
echo ""
echo "----> Should show: drwxr-xr-x ... recordings"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🔄 STEP 5: RESTART SERVICE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "sudo systemctl restart mecamera"
echo "sleep 5"
echo "sudo systemctl status mecamera | head -5"
echo ""
echo "----> Should show: 'active (running)'"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ STEP 6: VERIFY IN DASHBOARD"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Open browser: http://raspberrypi.local:8080"
echo "2. Should see: Live camera feed (NOT black screen)"
echo "3. Should NOT be jerky (should be smooth)"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "⚡ STEP 7: ENABLE FAST STREAMING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "In Dashboard:"
echo "  1. Click: ⚙️ Configure"
echo "  2. Scroll DOWN to: ⚡ Performance Settings (GREEN SECTION)"
echo "  3. Check: ✓ Use Fast Streaming (picamera2) - RECOMMENDED"
echo "  4. Set: Target Stream FPS = 15 (or 20-30)"
echo "  5. Click: 💾 Save Settings"
echo ""
echo "Service will restart automatically..."
echo "----> Dashboard should be much smoother (15-30 FPS)!"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎬 STEP 8: TEST MOTION DETECTION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Wave hand at camera for 10 seconds"
echo "2. Wait 30 seconds"
echo "3. Refresh dashboard (F5)"
echo "4. Scroll to: Recent Recordings"
echo "----> Should see motion_*.mp4 files!"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🔍 TROUBLESHOOTING COMMANDS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "# View current logs (real-time)"
echo "tail -f ~/ME_CAM-DEV/logs/mecam.log"
echo ""
echo "# Filter for specific issues:"
echo "tail -f ~/ME_CAM-DEV/logs/mecam.log | grep MOTION    # Motion detection"
echo "tail -f ~/ME_CAM-DEV/logs/mecam.log | grep CAMERA    # Camera issues"
echo "tail -f ~/ME_CAM-DEV/logs/mecam.log | grep STREAM    # Streaming"
echo "tail -f ~/ME_CAM-DEV/logs/mecam.log | grep ERROR     # Errors only"
echo ""
echo "# Check service status"
echo "sudo systemctl status mecamera"
echo ""
echo "# Restart service"
echo "sudo systemctl restart mecamera"
echo ""
echo "# Stop service"
echo "sudo systemctl stop mecamera"
echo ""
echo "# Check recordings"
echo "ls -lh ~/ME_CAM-DEV/recordings/"
echo ""
echo "# Test libcamera directly (5 second video)"
echo "libcamera-vid -t 5000 -o ~/test.mp4"
echo ""
echo "# Check if picamera2 works"
echo "python3 -c \"from picamera2 import Picamera2; c = Picamera2(); print('OK')\""
echo ""
echo "# Check CPU usage while running"
echo "top -b -n 1 | grep mecamera"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📊 VERIFICATION CHECKLIST"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Run these commands to verify everything works:"
echo ""
echo "# 1. Service running?"
echo "sudo systemctl status mecamera | grep active"
echo "# Should show: active (running)"
echo ""
echo "# 2. Fast streaming enabled?"
echo "grep 'use_fast_streamer' ~/ME_CAM-DEV/config/config.json"
echo "# Should show: \"use_fast_streamer\": true"
echo ""
echo "# 3. picamera2 available?"
echo "python3 -c \"from picamera2 import Picamera2; print('Yes')\""
echo "# Should show: Yes"
echo ""
echo "# 4. Recent videos?"
echo "ls ~/ME_CAM-DEV/recordings/ | wc -l"
echo "# Should show: >0"
echo ""
echo "# 5. Fast streaming in logs?"
echo "grep 'Fast streamer' ~/ME_CAM-DEV/logs/mecam.log | tail -1"
echo "# Should show: [CAMERA] Fast streamer initialized"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🚨 IF SOMETHING GOES WRONG"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "# 1. Check detailed error"
echo "tail -30 ~/ME_CAM-DEV/logs/mecam.log | grep -i error"
echo ""
echo "# 2. Full restart"
echo "sudo systemctl stop mecamera && sleep 2 && sudo systemctl start mecamera"
echo ""
echo "# 3. Kill stuck processes"
echo "pkill -f libcamera && sleep 2 && sudo systemctl restart mecamera"
echo ""
echo "# 4. Check camera works"
echo "libcamera-still -o ~/test.jpg && echo 'Camera OK' || echo 'Camera broken'"
echo ""
echo "# 5. Factory reset (LAST RESORT)"
echo "cd ~/ME_CAM-DEV && ./scripts/factory_reset.sh"
echo "# Then run setup again"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎓 UNDERSTANDING THE FIX"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Why was it slow? (1-2 FPS)"
echo "├─ Old method: Spawn libcamera-still for each frame (500-1000ms)"
echo "├─ Result: 1-2 FPS (one frame every 500-1000ms)"
echo "└─ Very jerky, like stop-motion video"
echo ""
echo "How does fast streaming work? (15-30 FPS)"
echo "├─ New method: Open camera once, capture continuously"
echo "├─ Frame always ready in memory (0ms access)"
echo "├─ Stream gets instant frames (35-50ms latency)"
echo "└─ Very smooth, like a phone camera"
echo ""
echo "Why both methods in code?"
echo "├─ picamera2 = fast (recommended) but requires newer Pi OS"
echo "├─ libcamera-still = slow but works everywhere"
echo "└─ Code auto-detects and uses best available"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📞 NEED MORE HELP?"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "See these documents:"
echo "  • DEPLOYMENT_FIXES_JAN13.md    ← Complete detailed guide"
echo "  • FIXES_SUMMARY.md               ← What changed (before/after)"
echo "  • docs/PERFORMANCE_GUIDE.md      ← Deep dive on performance"
echo "  • README.md                      ← Project overview"
echo ""
echo "View them:"
echo "  cat DEPLOYMENT_FIXES_JAN13.md"
echo "  less FIXES_SUMMARY.md"
echo ""
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ YOU'RE READY!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Run the quick start section at the top, then:"
echo "1. Enable fast streaming in dashboard settings"
echo "2. You should see smooth 15-30 FPS video!"
echo "3. Motion detection should save videos automatically"
echo ""
echo "Questions? Check the docs or review the logs!"
echo ""
